"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Channel_1_update.py']
DATA_FILES = []
OPTIONS = {}

setup(
    name="Channel_1_Ver_3",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
